export default [
  {
    id: "1",
    title: "Misty Mountain Lake",
    description:
      "A tranquil mountain lake at dawn with mist rising off the water.",
    img: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80",
    date: "2025-08-19",
    country: "Switzerland",
    view: "https://www.google.com/maps/search/Misty+Mountain+Lake+Switzerland",
  },
  {
    id: "2",
    title: "Serene Forest Creek",
    description: "A calm creek winding through a lush, green forest.",
    img: "https://tse4.mm.bing.net/th/id/OIP.KVccdHH8LfqPh1v8nPp2ygHaFc?pid=Api&P=0&h=220",
    date: "2025-08-18",
    country: "Canada",
    view: "https://www.google.com/maps/search/Serene+Forest+Creek+Canada",
  },
  {
    id: "3",
    title: "Monument Valley Sunset",
    description: "A striking sunset casting warm tones over Monument Valley.",
    img: "https://tse2.mm.bing.net/th/id/OIP.PvgxOjFVeygFWXbWucR9YAHaFj?pid=Api&P=0&h=220",
    date: "2025-08-17",
    country: "United States",
    view: "https://www.google.com/maps/search/Monument+Valley+United+States",
  },
  {
    id: "4",
    title: "Golden Hillside",
    description: "Rolling hills bathed in golden sunlight during the evening.",
    img: "https://tse3.mm.bing.net/th/id/OIP.cnNhUE80qn8kForw-LpmHwHaEH?pid=Api&P=0&h=220",
    date: "2025-08-16",
    country: "Italy",
    view: "https://www.google.com/maps/search/Golden+Hillside+Italy",
  },
  {
    id: "5",
    title: "Tropical Beach Paradise",
    description: "Soft waves lapping against a pristine tropical beach.",
    img: "https://tse3.mm.bing.net/th/id/OIP.dSkkYNntUGCpnXXEE7y0jQHaE4?pid=Api&P=0&h=220",
    date: "2025-08-15",
    country: "Maldives",
    view: "https://www.google.com/maps/search/Tropical+Beach+Paradise+Maldives",
  },
  {
    id: "6",
    title: "Foggy Forest Morning",
    description: "Trees silhouetted through thick morning fog.",
    img: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=600&q=80",
    date: "2025-08-14",
    country: "Finland",
    view: "https://www.google.com/maps/search/Foggy+Forest+Morning+Finland",
  },
  {
    id: "7",
    title: "Mountain Reflection",
    description: "Snow-capped peaks mirrored in a crystal-clear lake.",
    img: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=600&q=80",
    date: "2025-08-13",
    country: "Norway",
    view: "https://www.google.com/maps/search/Mountain+Reflection+Norway",
  },
  {
    id: "8",
    title: "Golden Desert Dunes",
    description: "Sunlit sand dunes stretching across the desert landscape.",
    img: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=600&q=80",
    date: "2025-08-12",
    country: "Morocco",
    view: "https://www.google.com/maps/search/Golden+Desert+Dunes+Morocco",
  },
  {
    id: "9",
    title: "Tropical Lagoon",
    description: "Turquoise lagoon surrounded by lush greenery.",
    img: "https://tse4.mm.bing.net/th/id/OIP.3_5SrXiAf6Bb6NX0KG1zTwHaE3?pid=Api&P=0&h=220",
    date: "2025-08-11",
    country: "Thailand",
    view: "https://www.google.com/maps/search/Tropical+Lagoon+Thailand",
  },
  {
    id: "10",
    title: "Starry Night by the Lake",
    description: "A star-filled sky reflecting on a calm lakeshore.",
    img: "https://tse4.mm.bing.net/th/id/OIP.iXfo_YrM4mXViT_kgvWWSgHaEo?pid=Api&P=0&h=220",
    date: "2025-08-10",
    country: "Australia",
    view: "https://www.google.com/maps/search/Starry+Night+by+the+Lake+Australia",
  },

  // ...continue similarly up to 50 entries with `view` included...
];
